#!/usr/bin/env bash
#A bash script that accepts two arguments

d_information () {
    ln=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $ln" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  d_information "$1" "www"
  d_information "$1" "lb-01"
  d_information "$1" "web-01"
  d_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  d_information "$1" "$2"
fi

