#!/usr/bin/env bash
# Configure Nginx server that redirect to another page

MESS="Hello world!"
RED= "\n\tlocation /redirect_me {\n\t return 301 https://www.youtube.com/watch?v=bgJ_1WuhUig; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y update
ufw allow 'Nginx HTTP'
echo "$MESS" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $RED" "$FILE"
service nginx restart
