#!/usr/bin/env bash
# install load balancer

function install() {
        command -v "$1" &> /dev/null

        #shellcheck disable=SC2181
        if [ $? -ne 0 ]; then
                sudo apt-get update -y -qq && \
                        sudo apt-get install -y "$1" -qq
        fi
}

install haproxy #install haproxy
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend nowayte-tech-frontend
    bind *:80
    default_backend nowayte-tech-backend

backend nowayte-tech-backend
    balance roundrobin
    server 277868-web-01 18.210.17.136:80 check
    server 277868-web-02 100.26.225.133:80 check
"
sudo dd status=none of=/etc/haproxy/haproxy.cfg
sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
