#!/usr/bin/env bash
# A script that generates a MySQL dump

password=$1
date=$(date +"%d-%m-%Y")
file="backup.sql"
arch_file="${date}.tar.gz"

msqldump -u root -p"${password}" --all-databases --single-transaction --quick --lock-tables=false > "${file}"

tar -czf "${file}" "${arch_file}"
