#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd using the while loop + IFS


while IFS=':' read -r username group home command user passwd info; do
	echo "The user $username is part of the $group gang, lives in $home and rides $command. $user place is proteected by the passcode $passwd, more info about the user here: $info"
done < /etc/passwd
