#!/usr/bin/env bash
# This Script loops from 1 to 10

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((i++))

done

