#!/usr/bin/env bash
# This is a script that display numbers from 1 to 20 

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	((i++))
done
