#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
i=1

while [ $i -le 12 ]
do
    echo "Hour: $i"
    m=1
    while [ $m -le 59 ]
    do
        echo $m
        m=$(( m + 1 ))
    done
    i=$(( i + 1 ))
done
