#!/usr/bin/env bash 
# A script that gives you information about the school file 

file="School"

if [ -e $file ]
then
	echo "school file exist"
	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is not empty"
	fi
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

